spring.application.name=warehouse-service
server.port=8081

# Sensor UDP configuration
sensor.temperature.port=3344
sensor.humidity.port=3355

# Central Monitoring Service endpoint
center.service.url=http://localhost:8080/api/measurements

# MQTT Configuration
mqtt.broker.url=tcp://localhost:1883

udp.buffer.size=1024

warehouse.id=default-warehouse
# Estimated RAM: ~112 bytes/msg (with warehouseId).
# 1k msg = ~112KB
# 10k msg = ~1.1MB
# 100k msg = ~11MB
queue.capacity=100000

logging.level.com.sensormonitor=WARN

# Defaults for MQTT and Sensor Parsing
mqtt.client.prefix=WarehousePublisher-
mqtt.reconnect.delay.ms=1000
sensor.field.separator=;
sensor.value.separator==
sensor.field.name.sensor_id=sensor_id
sensor.field.name.value=value

udp.bind.address=0.0.0.0

