spring.application.name=center-service
server.port=8080

# Alarm thresholds
thresholds.temperature=35.0
thresholds.humidity=50.0

# MQTT Configuration
mqtt.broker.url=tcp://localhost:1883
mqtt.topic=sensors/#
